"""
Utils Package

Centralized utilities for common operations across VidyaGuru.

Exports:
- Constants: Application configuration constants
- Validators: Common validation functions
- Email Service: Transactional email handling
- LLM Client: AI/Gemini integration
"""

from utils.constants import (
    CHALLENGE_CATEGORIES,
    CHALLENGE_DIFFICULTIES,
    SOLUTION_STATUSES,
    CHALLENGE_XP_REWARDS,
    SOLUTION_EVALUATION_WEIGHTS,
    RESUME_WORTHY_THRESHOLD,
    SUSPICION_LEVELS,
    VERIFICATION_TYPES,
    VERIFICATION_STATUSES,
    PLAGIARISM_DETECTION_THRESHOLD,
    RAPID_SUBMISSION_THRESHOLD,
    LARGE_PASTE_THRESHOLD,
    TYPING_PATTERN_ANOMALY_THRESHOLD,
    INTEGRITY_LEVELS,
    INTEGRITY_TRUST_SCORE_BOUNDARIES,
    LEARNING_PATH_STATUSES,
    PROFICIENCY_LEVELS,
    MODULE_TYPES,
    MENTOR_RESPONSE_STYLES,
    CONVERSATION_CONTEXTS,
    MENTOR_SESSION_TIMEOUT_SECONDS,
    USER_ROLES,
    ACCOUNT_STATUSES,
    PASSWORD_MIN_LENGTH,
    PASSWORD_REQUIRE_UPPERCASE,
    PASSWORD_REQUIRE_LOWERCASE,
    PASSWORD_REQUIRE_NUMBERS,
    PASSWORD_REQUIRE_SPECIAL,
    ACCESS_TOKEN_EXPIRE_MINUTES,
    REFRESH_TOKEN_EXPIRE_DAYS,
    TOKEN_TYPE,
    RATE_LIMITS,
    QUOTA_RESET_HOURS,
    TASK_SUBMISSION_TIMEOUT_MINUTES,
    VERIFICATION_CHALLENGE_EXPIRY_MINUTES,
    JOURNAL_ENTRY_AUTO_SAVE_INTERVAL_SECONDS,
    DEFAULT_PAGE_SIZE,
    MAX_PAGE_SIZE,
    MIN_PAGE_SIZE,
    EMAIL_TEMPLATES,
    FEATURES,
)

from utils.validators import (
    validate_email,
    validate_phone,
    validate_password,
    check_password_strength,
    validate_category,
    validate_difficulty,
    validate_categories_list,
    validate_role,
    validate_title,
    validate_description,
    validate_code,
    sanitize_text,
    validate_score,
    validate_percentage,
    validate_xp,
    validate_date,
    validate_future_date,
    validate_time_range,
    validate_uuid,
    validate_positive_int,
    validate_non_negative_int,
    validate_user_input,
    validate_challenge_input,
    validate_list_not_empty,
    validate_list_length,
)

from utils.email_service import EmailService

from utils.llm_client import LLMClient

__all__ = [
    # Constants
    "CHALLENGE_CATEGORIES",
    "CHALLENGE_DIFFICULTIES",
    "SOLUTION_STATUSES",
    "CHALLENGE_XP_REWARDS",
    "SOLUTION_EVALUATION_WEIGHTS",
    "RESUME_WORTHY_THRESHOLD",
    "SUSPICION_LEVELS",
    "VERIFICATION_TYPES",
    "VERIFICATION_STATUSES",
    "PLAGIARISM_DETECTION_THRESHOLD",
    "RAPID_SUBMISSION_THRESHOLD",
    "LARGE_PASTE_THRESHOLD",
    "TYPING_PATTERN_ANOMALY_THRESHOLD",
    "INTEGRITY_LEVELS",
    "INTEGRITY_TRUST_SCORE_BOUNDARIES",
    "LEARNING_PATH_STATUSES",
    "PROFICIENCY_LEVELS",
    "MODULE_TYPES",
    "MENTOR_RESPONSE_STYLES",
    "CONVERSATION_CONTEXTS",
    "MENTOR_SESSION_TIMEOUT_SECONDS",
    "USER_ROLES",
    "ACCOUNT_STATUSES",
    "PASSWORD_MIN_LENGTH",
    "PASSWORD_REQUIRE_UPPERCASE",
    "PASSWORD_REQUIRE_LOWERCASE",
    "PASSWORD_REQUIRE_NUMBERS",
    "PASSWORD_REQUIRE_SPECIAL",
    "ACCESS_TOKEN_EXPIRE_MINUTES",
    "REFRESH_TOKEN_EXPIRE_DAYS",
    "TOKEN_TYPE",
    "RATE_LIMITS",
    "QUOTA_RESET_HOURS",
    "TASK_SUBMISSION_TIMEOUT_MINUTES",
    "VERIFICATION_CHALLENGE_EXPIRY_MINUTES",
    "JOURNAL_ENTRY_AUTO_SAVE_INTERVAL_SECONDS",
    "DEFAULT_PAGE_SIZE",
    "MAX_PAGE_SIZE",
    "MIN_PAGE_SIZE",
    "EMAIL_TEMPLATES",
    "FEATURES",
    # Validators
    "validate_email",
    "validate_phone",
    "validate_password",
    "check_password_strength",
    "validate_category",
    "validate_difficulty",
    "validate_categories_list",
    "validate_role",
    "validate_title",
    "validate_description",
    "validate_code",
    "sanitize_text",
    "validate_score",
    "validate_percentage",
    "validate_xp",
    "validate_date",
    "validate_future_date",
    "validate_time_range",
    "validate_uuid",
    "validate_positive_int",
    "validate_non_negative_int",
    "validate_user_input",
    "validate_challenge_input",
    "validate_list_not_empty",
    "validate_list_length",
    # Services
    "EmailService",
    "LLMClient",
]
